title: "Modern GenAI in Software Development"
description: "CSCI 6907/4907, Fall 2026, George Washington University"

# ---- EDIT THESE TWO LINES IF YOUR ORG OR REPO NAME IS DIFFERENT ----
url: "https://modern-genai-se.github.io"
baseurl: "/f2026"
# --------------------------------------------------------------------

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

color_scheme: light
search_enabled: true
heading_anchors: true

nav_external_links:
  - title: "Blackboard"
    url: https://blackboard.gwu.edu
  - title: "Slack Channel"
    url: https://join.slack.com/t/moderngenaiin-xum1052/shared_invite/zt-47qafv1qd-YNvhxpUUa0BWkAyWxb2ljQ

footer_content: "Courtney Miller, George Washington University."

exclude:
  - README.md
